contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #gapseqflow channel"
    url: https://nfcore.slack.com/channels/gapseqflow
    about: Discussion about the nf-core/gapseqflow pipeline
